# Generated by Django 4.2.5 on 2023-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
